---
  metaData: 
    author: "d3fkon"
    git-repo: "https://github.com/d3fkon/repozx1"
    approval: 
      approved-by: "d3fkon"
      approval-date: 1564511422340
  job: 
    job-name: "d3fkonxrepozx1"
    config: 
      pre-unit-test: "no"
      post-unit-test: "yes"
      dev: "no"
      prod: "yes"
      fresh: "no"
